name: nbgapi
description: nbg.ge currency rate api provider
version: 0.0.2
homepage: https://github.com/valkiara/nbgapi

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  xml: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: